package com.vijay.test;

import java.awt.Button;
import java.sql.Date;

/*
	3 important ways to create object of java.lang.Class class
		> It has only one constructor defined and is private.
		1) using static method forName("----")
		2) using getClass() method of Object class on any class
		3) using .class property generated by compiler for every class
	
*/
public class GetBeanTest {

	public static void main(String[] args) throws Exception{
		
	Class c1=Class.forName("java.util.Date");
	System.out.println("c1 :: "+c1.hashCode()+c1.toString());
	
	Button b= new Button();
	Class c2= b.getClass();
	System.out.println("c2 :: "+c2.hashCode()+c2.toString());
	
	Class c3=Date.class;
	Class c4=GetBeanTest.class;
	
	System.out.println("c3 :: "+c3.hashCode()+c3.toString());
	System.out.println("c4 :: "+c4.hashCode()+c4.toString());
		
	}
}
